<!--Following codes are majorly generated by chatgpt-->
<template>
    <div class="draggable-button" :style="{ bottom: posY + 'px', right: posX + 'px' }" @mousedown="startDrag" @touchstart="startDrag">
        <img class="logo" src="@/assets/logo.png">
    </div>
  </template>
  
  <script>
  export default {
    data() {
      return {
        posX: 0,
        posY: 0,
        isDragging: false,
        startX: 0,
        startY: 0
      };
    },
    props: {

      bottom: {
        type: Number,
        default: 32
      },
      right: {
        type: Number,
        default: 32
      }
    },
    mounted() {
      this.posX = this.bottom;
      this.posY = this.right;
    },

    methods: {
      startDrag(event) {
        //event.preventDefault();

        this.isDragging = true;

        if(event.type == 'mousedown') {
            this.startX = event.clientX + this.posX; // screenWidth: document.body.clientWidth;
            this.startY = event.clientY + this.posY; // screenHeight: document.body.clientHeight ;

            document.addEventListener('mousemove', this.handleDrag);
            document.addEventListener('mouseup', this.stopDrag);

            //console.log(this.startX + '|' + this.startY)
        }

        if(event.type == 'touchstart') {
            this.startX = event.touches[0].clientX + this.posX; // screenWidth: document.body.clientWidth;
            this.startY = event.touches[0].clientY + this.posY; // screenHeight: document.body.clientHeight ;

            // mobile touch move
            document.addEventListener('touchmove', this.handleDrag);
            document.addEventListener('touchend', this.stopDrag);

            //console.log(this.startX + '|' + this.startY)
        }

      },
      handleDrag(event) {
        if (this.isDragging) {
            if(event.type == 'mousemove') {
                this.posX = this.startX - event.clientX; //event.clientX - this.startX;
                this.posY = this.startY - event.clientY; //event.clientY - this.startY;                
            }

            if(event.type == 'touchmove') {
                this.posX = this.startX - event.touches[0].clientX; //event.clientX - this.startX;
                this.posY = this.startY - event.touches[0].clientY; //event.clientY - this.startY;                     
            }
        }
      },
      stopDrag() {
        this.isDragging = false;
        document.removeEventListener('mousemove', this.handleDrag);
        document.removeEventListener('mouseup', this.stopDrag);

        document.removeEventListener('touchmove', this.handleDrag);
        document.removeEventListener('touchend', this.stopDrag);
      }
    }
  };
  </script>
  
  <style scoped>
  .draggable-button {
    position: fixed;
    cursor: move;
    
    box-shadow: rgb(0 0 0 / 30%) 2px 2px 4px;
    height: 48px;
    width: 48px;
    border-radius: 24px;    
  }

  .logo {
    width: 40px;
    margin: 4px;
  }
  </style>